singleQuote: false
semi: true
printWidth: 100
trailingComma: all
plugins:
  - "prettier-plugin-packagejson"
  - "prettier-plugin-tailwindcss"
tailwindFunctions: ["clsx", "cva", "cx", "cn"]
overrides:
  - files: "package.json"
    options:
      packageSortOrder: ["name", "productName", "description"]
